### ISSUE TITLE
Issue with pheremone age detection

### ISSUE THREAD

**Issue by nekokiwa** [SebLague/Ant-Simulation#1]
There appears to be an issue when determining the age of a pheremone while searching for food or returning home where they check `pheremoneEntries[i]` instead of `pheremoneEntries[j]`, which would cause them to read the age of all pheremones as the same for each sensor. This issue appears around line 340 in the Ant.cs file.

**Comment by nekokiwa** [comment]
Of course you're probably not planning on returning to this anyway but I felt I should point it out anyway.

**Comment by SebLague** [comment]
Eagle eyes! Thank you, I've fixed it.
